trigger:
- master
- develop
- feature/*

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  restoreBuildProjects: '**/*.csproj'
  testProjects: '**/*[Tt]ests/*.csproj'

stages:
- stage: BuildApplication
  displayName: 'Build Application'

  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
        command: restore
        projects: '$(restoreBuildProjects)'

    - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
        projects: '$(restoreBuildProjects)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
        command: test
        projects: '$(testProjects)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()