version: '3.9'

services:
  blazor:
    image: ${DOCKER_REGISTRY-}tsa-coding-submissions-blazor
    build:
      context: .
      dockerfile: Tsa.Coding.Submissions.Blazor/Dockerfile
    depends_on:
      - identity
      - rabbitmq
      - web-api

  db:
    image: ${DOCKER_REGISTRY-}tsa-coding-submissions-db:dev
    build:
      context: docker/database/.
      dockerfile: Dockerfile

  identity:
    image: webstorm.azurecr.io/tsa/coding/submissions/identity:0
    hostname: identity
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management

  web-api:
    image: ${DOCKER_REGISTRY-}tsa-coding-submissions-webapi
    build:
      context: .
      dockerfile: Tsa.Coding.Submissions.WebApi/Dockerfile
    depends_on:
      - db
      - identity