name: build-application-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  TEST_VARIABLE: ""

jobs:
  buildApplciations:
    name: "Build .NET Applciations"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore Web API Project
      run: dotnet restore ./src/Tsa.CodingChallenge.Submissions.WebApi/Tsa.CodingChallenge.Submissions.WebApi.csproj

    - name: Restore Blazor Project
      run: dotnet restore ./src/Tsa.CodingChallenge.Submissions.Blazor/Tsa.CodingChallenge.Submissions.Blazor.csproj

    - name: Restore Unit Tests Project
      run: dotnet restore ./src/Tsa.CodingChallenge.Submissions.UnitTests/Tsa.CodingChallenge.Submissions.UnitTests.csproj

    - name: Build Web API Project
      run: dotnet build ./src/Tsa.CodingChallenge.Submissions.WebApi/Tsa.CodingChallenge.Submissions.WebApi.csproj --configuration Release --no-restore

    - name: Build Blazor Project
      run: dotnet build ./src/Tsa.CodingChallenge.Submissions.Blazor/Tsa.CodingChallenge.Submissions.Blazor.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ./src/Tsa.CodingChallenge.Submissions.UnitTests/Tsa.CodingChallenge.Submissions.UnitTests.csproj --no-restore --verbosity normal --filter "TestCategory=UnitTest"

  buildDatabase:
    name: "Build Database DACPAC"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Database DACPAC
        uses: msbuild .\src\Tsa.CodingChallenge.Submissions.Database\Tsa.CodingChallenge.Submissions.Database.sqlproj /t:Build /p:SolutionDir=.\src /p:configuration=release

      - uses: actions/upload-artifact@v2
        with:
          name: database-docker
          path: docker/database

      - uses: actions/upload-artifact@v2
        with:
          name: database-dacpac
          path: src/*.Database/**/*.dacpac
